name: qkcli-integration-test

on: [push]

jobs:
  mnt-test-using-qkcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # In the future, add it as a submodule
          repository: QuarkChain/qkcli
          ref: master
          token: ${{ secrets.QKCLI_PAT }}
          path: qkcli
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.14.4"
      - run: go version
      - run: |
          git clone https://github.com/QuarkChain/goquarkchain
          cd goquarkchain && git checkout remotes/origin/users/chunfengSun/add-qkc-cli-test && cd -

          cp goquarkchain/tests/ci-qkcli/runner.sh qkcli/tester/runner.sh
          chmod +x parallel_executor.sh && ./parallel_executor.sh
